copy_mode: False
nnodes: 1
nproc_per_node: 2
model_name: gokmen_quadratic
model_type: deep
batch_size: 256
total_training_steps: 100000 
lr: 0.0001
rho: 7.0
final_timesteps: 250
initial_timesteps: 20
img_channels: 3
base_channels: 192
num_res_blocks: 8
groupnorm: 16
num_heads: 8
num_head_channels: 64
use_scale_shift_norm: False
use_new_attention_order: False
use_conv: False
use_conv_up_down: False
use_flash_attention: True
attention_resolutions: [32,16,8]
dropout: 0.02
image_size: 32
img_dimension: 3